import { AsyncLocalStorage } from "node:async_hooks";
import fs from "node:fs";
import path from "node:path";
import { seed } from "./seed";

/**
 * Storage layer: PostgreSQL.
 * - DATABASE_URL / POSTGRES_URL set (Vercel Postgres, Neon, Supabase, Railway…): a real server.
 * - Otherwise: PGlite, an embedded Postgres stored in ./data/pg, so local
 *   development needs no setup. Same SQL dialect in both cases.
 * Queries use "?" placeholders; they are converted to $1, $2… here.
 * All timestamps are unix milliseconds, all money is integer cents (USD).
 */

const SCHEMA = `
CREATE TABLE IF NOT EXISTS cities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  name_en TEXT NOT NULL,
  name_ru TEXT NOT NULL,
  in_en TEXT NOT NULL,             -- "in Paris"
  in_ru TEXT NOT NULL,             -- "в Париже"
  country TEXT NOT NULL DEFAULT '',
  lat DOUBLE PRECISION NOT NULL,
  lon DOUBLE PRECISION NOT NULL,
  tz TEXT NOT NULL,
  hidden BIGINT NOT NULL DEFAULT 0,
  fail_count BIGINT NOT NULL DEFAULT 0,
  last_poll_at BIGINT
);

CREATE TABLE IF NOT EXISTS event_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  name_en TEXT NOT NULL,
  name_ru TEXT NOT NULL,
  title_en TEXT NOT NULL,          -- "The next rain {in}"
  title_ru TEXT NOT NULL,
  kind TEXT NOT NULL,              -- rain | snow | thunder | sunrise | meteor
  threshold DOUBLE PRECISION NOT NULL DEFAULT 0,        -- mm/h for precipitation types
  min_duration_min BIGINT NOT NULL DEFAULT 10,
  end_quiet_min BIGINT NOT NULL DEFAULT 30,
  recurrence TEXT NOT NULL,        -- continuous | season | window | manual
  season_start TEXT,               -- MM-DD for "first X of season"
  window_start TEXT,               -- MM-DD HH:mm local, for window events
  window_end TEXT,                 -- MM-DD HH:mm local (may cross new year)
  rule_en TEXT NOT NULL,
  rule_ru TEXT NOT NULL,
  start_text_en TEXT NOT NULL,
  start_text_ru TEXT NOT NULL,
  sort BIGINT NOT NULL DEFAULT 0
);

-- A series of moments sold in one city ("next rain in Paris") with its price.
CREATE TABLE IF NOT EXISTS offerings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  city_id BIGINT NOT NULL REFERENCES cities(id),
  event_type_id BIGINT NOT NULL REFERENCES event_types(id),
  price_cents BIGINT NOT NULL,
  sale_type TEXT NOT NULL DEFAULT 'fixed',   -- fixed | auction
  auction_step_cents BIGINT NOT NULL DEFAULT 2500,
  auction_days BIGINT NOT NULL DEFAULT 7,
  active BIGINT NOT NULL DEFAULT 1,
  UNIQUE(city_id, event_type_id)
);

CREATE TABLE IF NOT EXISTS moments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  offering_id BIGINT REFERENCES offerings(id),
  city_id BIGINT NOT NULL REFERENCES cities(id),
  event_type_id BIGINT NOT NULL REFERENCES event_types(id),
  seq BIGINT NOT NULL DEFAULT 1,
  label_en TEXT,                   -- custom one-off moments
  label_ru TEXT,
  price_cents BIGINT NOT NULL,
  sale_type TEXT NOT NULL DEFAULT 'fixed',
  status TEXT NOT NULL DEFAULT 'on_sale',    -- on_sale | sold | live | completed | expired | cancelled
  locked_until BIGINT,
  earliest_start BIGINT,          -- monitoring starts at (season start / window start)
  window_end BIGINT,              -- the event must happen before (window events)
  hits BIGINT NOT NULL DEFAULT 0,
  candidate_start BIGINT,
  last_hit_at BIGINT,
  started_at BIGINT,
  ended_at BIGINT,
  max_intensity DOUBLE PRECISION,
  min_temp DOUBLE PRECISION,
  max_temp DOUBLE PRECISION,
  confirmed_by TEXT,               -- sources that confirmed the start
  created_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS moments_status ON moments(status);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  name TEXT,
  stripe_customer_id TEXT,
  card_on_file BIGINT NOT NULL DEFAULT 0,
  created_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  token TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id),
  expires_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS login_codes (
  email TEXT NOT NULL,
  code TEXT NOT NULL,
  expires_at BIGINT NOT NULL,
  attempts BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY,
  moment_id BIGINT NOT NULL REFERENCES moments(id),
  user_id BIGINT REFERENCES users(id),
  auction_id BIGINT,
  token TEXT UNIQUE NOT NULL,
  lang TEXT NOT NULL DEFAULT 'en',
  buyer_email TEXT NOT NULL,
  giver_name TEXT,
  recipient_name TEXT NOT NULL,
  recipient_contact TEXT NOT NULL,
  message TEXT,
  hide_message BIGINT NOT NULL DEFAULT 0,
  send_at BIGINT,                 -- null = right after payment
  sent_at BIGINT,
  notify_channel TEXT,             -- chosen by recipient: email | sms | push | none
  status TEXT NOT NULL DEFAULT 'pending',  -- pending | paid | refunded | cancelled
  amount_cents BIGINT NOT NULL,
  refund_cents BIGINT,
  stripe_session_id TEXT,
  stripe_payment_intent TEXT,
  opened_at BIGINT,
  deleted_by_recipient BIGINT NOT NULL DEFAULT 0,
  created_at BIGINT NOT NULL,
  paid_at BIGINT
);
CREATE INDEX IF NOT EXISTS orders_email ON orders(buyer_email);
CREATE INDEX IF NOT EXISTS orders_moment ON orders(moment_id);

CREATE TABLE IF NOT EXISTS measurements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city_id BIGINT NOT NULL,
  moment_id BIGINT,
  source TEXT NOT NULL,
  taken_at BIGINT NOT NULL,
  temperature DOUBLE PRECISION,
  precipitation DOUBLE PRECISION,
  snowfall DOUBLE PRECISION,
  weather_code BIGINT,
  condition_met BIGINT NOT NULL DEFAULT 0,
  disputed BIGINT NOT NULL DEFAULT 0,
  resolution TEXT,                 -- confirmed | rejected (admin)
  note TEXT,
  raw TEXT
);
CREATE INDEX IF NOT EXISTS measurements_moment ON measurements(moment_id, taken_at);
CREATE INDEX IF NOT EXISTS measurements_city ON measurements(city_id, taken_at);

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel TEXT NOT NULL,           -- email | sms | push
  recipient TEXT NOT NULL,
  subject TEXT,
  body TEXT NOT NULL,
  kind TEXT NOT NULL,
  order_id TEXT,
  status TEXT NOT NULL DEFAULT 'queued',  -- queued | sent | logged | failed
  error TEXT,
  created_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS auctions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  moment_id BIGINT NOT NULL REFERENCES moments(id),
  start_cents BIGINT NOT NULL,
  step_cents BIGINT NOT NULL,
  starts_at BIGINT NOT NULL,
  ends_at BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active', -- active | awaiting_payment | sold | unsold | cancelled
  winner_bid_id BIGINT,
  pay_deadline BIGINT,
  created_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS bids (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auction_id BIGINT NOT NULL REFERENCES auctions(id),
  user_id BIGINT NOT NULL REFERENCES users(id),
  amount_cents BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active', -- active | won | forfeited
  created_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author TEXT NOT NULL,
  text_en TEXT NOT NULL,
  text_ru TEXT NOT NULL,
  visible BIGINT NOT NULL DEFAULT 1,
  created_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS faq (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  q_en TEXT NOT NULL, a_en TEXT NOT NULL,
  q_ru TEXT NOT NULL, a_ru TEXT NOT NULL,
  sort BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sim_overrides (
  city_id BIGINT PRIMARY KEY,
  precipitation DOUBLE PRECISION,
  weather_code BIGINT,
  until BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS kv (key TEXT PRIMARY KEY, value TEXT);
`;

type Param = null | number | string;
type Row = Record<string, unknown>;

interface Conn {
  query(sql: string, params: Param[]): Promise<{ rows: Row[]; count: number }>;
  exec(sql: string): Promise<void>;
  transaction<T>(fn: (c: Conn) => Promise<T>): Promise<T>;
}

function toPg(sql: string) {
  let i = 0;
  return sql.replace(/\?/g, () => `$${++i}`);
}

async function connectServer(url: string): Promise<Conn> {
  const { default: postgres } = await import("postgres");
  const local = /localhost|127\.0\.0\.1/.test(url);
  const sql = postgres(url, {
    max: Number(process.env.DATABASE_POOL_MAX ?? 5),
    prepare: false, // works behind pgbouncer / Neon pooler
    ssl: local ? false : "require",
    idle_timeout: 20,
    // int8, numeric -> JS numbers (ids, timestamps and cents fit safely)
    types: {
      bigint: { to: 20, from: [20, 1700], serialize: (v: number) => String(v), parse: (v: string) => Number(v) },
    },
  });
  const wrap = (q: typeof sql): Conn => ({
    async query(text, params) {
      const res = await q.unsafe(toPg(text), params as never[]);
      return { rows: res as unknown as Row[], count: res.count ?? 0 };
    },
    async exec(text) {
      await q.unsafe(text);
    },
    async transaction(fn) {
      return (await sql.begin((t) => fn(wrap(t as unknown as typeof sql)))) as never;
    },
  });
  return wrap(sql);
}

async function connectEmbedded(): Promise<Conn> {
  const { PGlite } = await import("@electric-sql/pglite");
  const dir = process.env.PGLITE_DIR || path.join(process.cwd(), "data", "pg");
  fs.mkdirSync(path.dirname(dir), { recursive: true });
  const pg = await PGlite.create(dir);
  type Q = Pick<typeof pg, "query" | "exec">;
  const wrap = (q: Q): Conn => ({
    async query(text, params) {
      const res = await q.query<Row>(toPg(text), params);
      return { rows: res.rows, count: res.affectedRows ?? res.rows.length };
    },
    async exec(text) {
      await q.exec(text);
    },
    async transaction(fn) {
      return pg.transaction((t) => fn(wrap(t)));
    },
  });
  return wrap(pg);
}

const g = globalThis as unknown as { __momentDb?: Promise<Conn> };
const txStore = new AsyncLocalStorage<Conn>();

async function init(): Promise<Conn> {
  const url = process.env.DATABASE_URL || process.env.POSTGRES_URL;
  if (!url && process.env.VERCEL) {
    throw new Error("DATABASE_URL is not set. Add a Postgres database (Neon / Supabase) to the Vercel project.");
  }
  const conn = url ? await connectServer(url) : await connectEmbedded();
  await conn.exec(SCHEMA);
  await conn.transaction(async (c) => {
    // Several cold-starting instances may race here; the lock serializes them.
    await c.query("SELECT pg_advisory_xact_lock(724301)", []);
    const done = await c.query("SELECT value FROM kv WHERE key = 'seeded'", []);
    if (done.rows.length) return;
    await txStore.run(c, () => seed());
    await c.query("INSERT INTO kv(key, value) VALUES ('seeded', '1')", []);
  });
  return conn;
}

async function conn(): Promise<Conn> {
  const inTx = txStore.getStore();
  if (inTx) return inTx;
  if (!g.__momentDb) {
    g.__momentDb = init().catch((e) => {
      g.__momentDb = undefined;
      throw e;
    });
  }
  return g.__momentDb;
}

export async function all<T>(sql: string, ...params: Param[]): Promise<T[]> {
  return (await (await conn()).query(sql, params)).rows as T[];
}
export async function one<T>(sql: string, ...params: Param[]): Promise<T | undefined> {
  return (await all<T>(sql, ...params))[0];
}
/** Runs a statement; `changes` is the number of affected rows. */
export async function run(sql: string, ...params: Param[]): Promise<{ changes: number }> {
  const res = await (await conn()).query(sql, params);
  return { changes: res.count };
}
/** INSERT … and return the new row id. */
export async function insert(sql: string, ...params: Param[]): Promise<number> {
  const res = await (await conn()).query(`${sql} RETURNING id`, params);
  return Number(res.rows[0].id);
}

/** Runs `fn` in a transaction; every query inside it goes through the same connection. */
export async function tx<T>(fn: () => Promise<T>): Promise<T> {
  const current = txStore.getStore();
  if (current) return fn();
  const c = await conn();
  return c.transaction((t) => txStore.run(t, fn));
}

export async function kvGet(key: string): Promise<string | undefined> {
  return (await one<{ value: string }>("SELECT value FROM kv WHERE key = ?", key))?.value;
}
export async function kvSet(key: string, value: string) {
  await run("INSERT INTO kv(key, value) VALUES (?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value", key, value);
}
